trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- task: DownloadSecureFile@1
  displayName: 'Download SSH private key'
  inputs:
    secureFile: 'ubuntuexample3.pem'

- task: Bash@3
  displayName: 'Connect to AWS EC2 and Install Jupyter Notebook'
  inputs:
    targetType: 'inline'
    script: |
      # Set permissions on the downloaded SSH private key file
      echo "Setting permissions on SSH private key file..."
      chmod 600 $(Agent.TempDirectory)/ubuntuexample3.pem

      # Connect to AWS EC2 instance via SSH, ignoring host key verification
      echo "Connecting to AWS EC2 instance via SSH..."
      ssh -o StrictHostKeyChecking=no -i $(Agent.TempDirectory)/ubuntuexample3.pem ubuntu@3.6.94.199 'sudo apt update && sudo apt install -y python3-pip python3-dev'

      # Install Jupyter Notebook using pip
      echo "Installing Jupyter Notebook..."
      ssh -i $(Agent.TempDirectory)/ubuntuexample3.pem ubuntu@3.6.94.199 'sudo pip3 install jupyter'
